Repository ethersphere/swarm-desktop, pull requests merged in 2022-06, with the labels that each got.

#85 feat: add keep alive
  src/index.ts
  src/launcher.ts
  src/lifecycle.ts
Labels: pull-request

#91 feat: persistant logs
  README.md
  src/logger.ts
  src/path.ts
Labels: pull-request

#93 feat: add peers endpoint
  src/server.ts
Labels: pull-request

#90 chore: release 0.6.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: pull-request, autorelease: pending

#95 feat: add new static folder location
  src/downloader.ts
Labels: pull-request

#96 chore: release 0.7.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: pull-request, autorelease: pending

#102 fix: support multiple path check when determining download
  src/downloader.ts
Labels: pull-request

#104 fix: do not open restart
  src/browser.ts
Labels: pull-request

#103 chore: release 0.8.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: pull-request, autorelease: pending

#107 fix: add support for latest bee log
  src/launcher.ts
Labels: pull-request

#105 feat: sentry support
  .github/workflows/release.yml
  README.md
  package-lock.json
  package.json
  src/.sentry.json
  src/index.ts
  src/logger.ts
  src/server.ts
Labels: pull-request

#113 feat: add new static version and auto open ui
  src/downloader.ts
  src/electron.ts
  src/index.ts
Labels: pull-request

#111 chore: release 0.9.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: pull-request, autorelease: pending

#114 fix: use sentry release only on linux release
  .github/workflows/release.yml
Labels: pull-request

#116 feat: add new icons
  icon.icns
  icon.png
Labels: pull-request

#117 chore: release 0.10.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: pull-request, autorelease: pending

#120 chore: release 0.11.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: pull-request, autorelease: pending

#122 chore: release 0.11.2
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#123 chore: release 0.11.3
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#124 chore: release 0.11.4
  CHANGELOG.md
  package-lock.json
  package.json
Labels: pull-request, autorelease: pending

#125 chore: release 0.11.5
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#126 chore: release 0.12.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#127 chore: release 0.12.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#129 feat: expose desktop version
  src/server.ts
Labels: pull-request

#128 docs: update changed dirs paths
  README.md
Labels: pull-request

#131 chore: update assets
  src/downloader.ts
Labels: pull-request

#132 feat: asset version check
  src/index.ts
Labels: pull-request

#134 chore: assets update
  src/downloader.ts
Labels: pull-request

#133 chore: release 0.14.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: pull-request, autorelease: pending

#136 docs: release process
  README.md
Labels: pull-request

#142 chore: assets update
  src/downloader.ts
Labels: pull-request

#143 ci: non-draft prereleases
  package.json
Labels: pull-request

#147 feat: improved electron-reforger config
  .github/workflows/release.yml
  assets/entitlements.plist
  assets/icon.icns
  forge.config.js
  icon.png
  package.json
Labels: pull-request

#148 chore: update bee
  src/downloader.ts
Labels: pull-request

#149 chore: codeowners
  CODEOWNERS
  README.md
Labels: pull-request

#150 ci: update release please
  .github/workflows/release_github.yaml
Labels: pull-request

#151 ci: install deps for installer
  .github/workflows/pre-release.yml
  .github/workflows/release.yml
  .github/workflows/tests.yaml
Labels: pull-request

#155 ci: use LF EOL in Windows
  .gitattributes
Labels: pull-request

#156 feat: top level error catch
  src/index.ts
Labels: pull-request

#137 feat: code signing
  .github/tools/add-macos-cert.sh
  .github/workflows/release.yml
  forge.config.js
Labels: pull-request

#159 ci: fix sentry release
  .github/workflows/pre-release.yml
  .github/workflows/release.yml
Labels: pull-request

#161 ci: fix another sentry release
  .github/workflows/pre-release.yml
Labels: pull-request

#164 build: minimize app size
  .github/workflows/pre-release.yml
  package.json
Labels: pull-request

#165 ci: don't remove dev
  .github/workflows/pre-release.yml
Labels: pull-request

#166 ci: rimraf
  .github/workflows/pre-release.yml
Labels: pull-request

#167 ci: npx rimraf
  .github/workflows/pre-release.yml
Labels: pull-request

#168 ci: disable code signing
  forge.config.js
Labels: pull-request

#157 fix(installer): install estimate fix
  installer/src/App.tsx
Labels: pull-request

#171 build: windows build improvements
  assets/icon.ico
  forge.config.js
  package.json
Labels: pull-request

#172 build: re-enable code-signing
  forge.config.js
  package.json
Labels: pull-request

#173 build: fix macos icon
  forge.config.js
Labels: pull-request

#174 fix: remove ellipsis from main text
  installer/src/App.tsx
Labels: pull-request

#175 feat: add token price endpoint
  src/server.ts
Labels: pull-request

#176 build: fix macos dmg icon
  forge.config.js
Labels: pull-request

#178 fix: squirrel startup test
  src/index.ts
Labels: pull-request

#179 ci: have sentry enabled bee dashboard
  .github/workflows/pre-release.yml
  .github/workflows/release.yml
Labels: pull-request

#146 feat: auto update support
  package-lock.json
  package.json
  src/index.ts
  src/server.ts
Labels: pull-request
